AST_NODES =  \
	  ast/array-exp.hh ast/array-exp.hxx ast/array-exp.cc  \
	  ast/array-ty.hh ast/array-ty.hxx ast/array-ty.cc  \
	  ast/assign-exp.hh ast/assign-exp.hxx ast/assign-exp.cc  \
	  ast/ast.hh ast/ast.hxx ast/ast.cc  \
	  ast/break-exp.hh ast/break-exp.hxx ast/break-exp.cc  \
	  ast/call-exp.hh ast/call-exp.hxx ast/call-exp.cc  \
	  ast/cast-exp.hh ast/cast-exp.hxx ast/cast-exp.cc  \
	  ast/cast-var.hh ast/cast-var.hxx ast/cast-var.cc  \
	  ast/class-ty.hh ast/class-ty.hxx ast/class-ty.cc  \
	  ast/dec.hh ast/dec.hxx ast/dec.cc  \
	  ast/decs-list.hh ast/decs-list.hxx ast/decs-list.cc  \
	  ast/exp.hh ast/exp.hxx ast/exp.cc  \
	  ast/field.hh ast/field.hxx ast/field.cc  \
	  ast/field-init.hh ast/field-init.hxx ast/field-init.cc  \
	  ast/field-var.hh ast/field-var.hxx ast/field-var.cc  \
	  ast/for-exp.hh ast/for-exp.hxx ast/for-exp.cc  \
	  ast/function-dec.hh ast/function-dec.hxx ast/function-dec.cc  \
	  ast/if-exp.hh ast/if-exp.hxx ast/if-exp.cc  \
	  ast/int-exp.hh ast/int-exp.hxx ast/int-exp.cc  \
	  ast/let-exp.hh ast/let-exp.hxx ast/let-exp.cc  \
	  ast/method-call-exp.hh ast/method-call-exp.hxx ast/method-call-exp.cc  \
	  ast/method-dec.hh ast/method-dec.hxx ast/method-dec.cc  \
	  ast/name-ty.hh ast/name-ty.hxx ast/name-ty.cc  \
	  ast/nil-exp.hh ast/nil-exp.hxx ast/nil-exp.cc  \
	  ast/object-exp.hh ast/object-exp.hxx ast/object-exp.cc  \
	  ast/op-exp.hh ast/op-exp.hxx ast/op-exp.cc  \
	  ast/record-exp.hh ast/record-exp.hxx ast/record-exp.cc  \
	  ast/record-ty.hh ast/record-ty.hxx ast/record-ty.cc  \
	  ast/seq-exp.hh ast/seq-exp.hxx ast/seq-exp.cc  \
	  ast/simple-var.hh ast/simple-var.hxx ast/simple-var.cc  \
	  ast/string-exp.hh ast/string-exp.hxx ast/string-exp.cc  \
	  ast/subscript-var.hh ast/subscript-var.hxx ast/subscript-var.cc  \
	  ast/ty.hh ast/ty.hxx ast/ty.cc  \
	  ast/type-dec.hh ast/type-dec.hxx ast/type-dec.cc  \
	  ast/var.hh ast/var.hxx ast/var.cc  \
	  ast/var-dec.hh ast/var-dec.hxx ast/var-dec.cc  \
	  ast/while-exp.hh ast/while-exp.hxx ast/while-exp.cc
